-- =========================================================
-- HELLOBikes DATABASE
-- Fresh database schema
-- =========================================================

create extension if not exists pgcrypto;

-- =========================================================
-- PROFILES
-- =========================================================

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text unique not null,
    full_name text not null,
    phone text,
    country text,
    referral_code text unique not null,
    referred_by uuid references public.profiles(id) on delete set null,
    role text not null default 'user'
        check (role in ('user', 'admin')),
    kyc_status text not null default 'pending'
        check (
            kyc_status in (
                'pending',
                'submitted',
                'approved',
                'rejected'
            )
        ),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- =========================================================
-- WALLETS
-- =========================================================

create table if not exists public.wallets (
    id uuid primary key default gen_random_uuid(),
    user_id uuid unique not null
        references public.profiles(id)
        on delete cascade,
    balance_usd numeric(14,2) not null default 0,
    earnings_usd numeric(14,2) not null default 0,
    referral_earnings_usd numeric(14,2) not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- =========================================================
-- BIKE PACKAGES
-- =========================================================

create table if not exists public.bike_packages (
    id bigint generated by default as identity primary key,
    name text not null,
    bikes integer not null check (bikes > 0),
    price numeric(14,2) not null check (price > 0),
    amount_usd numeric(14,2) not null check (amount_usd > 0),
    status text not null default 'active'
        check (status in ('active', 'inactive')),
    created_at timestamptz not null default now()
);

-- =========================================================
-- ORDERS
-- =========================================================

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    user_id uuid not null
        references public.profiles(id)
        on delete cascade,
    package_id bigint not null
        references public.bike_packages(id),
    fulfillment text not null default 'rental'
        check (
            fulfillment in (
                'rental',
                'delivery'
            )
        ),
    amount_usd numeric(14,2) not null
        check (amount_usd > 0),
    status text not null default 'pending'
        check (
            status in (
                'pending',
                'paid',
                'processing',
                'completed',
                'cancelled'
            )
        ),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- =========================================================
-- RENTALS
-- =========================================================

create table if not exists public.rentals (
    id bigint generated by default as identity primary key,
    user_id uuid not null
        references public.profiles(id)
        on delete cascade,
    order_id bigint not null
        references public.orders(id)
        on delete cascade,
    start_date date,
    end_date date,
    status text not null default 'pending'
        check (
            status in (
                'pending',
                'active',
                'completed',
                'cancelled'
            )
        ),
    created_at timestamptz not null default now()
);

-- =========================================================
-- DEPOSITS
-- =========================================================

create table if not exists public.deposits (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null
        references public.profiles(id)
        on delete cascade,
    network text not null
        check (
            network in (
                'TRC20',
                'BEP20'
            )
        ),
    amount_usd numeric(14,2) not null
        check (amount_usd >= 10),
    tx_hash text,
    status text not null default 'pending'
        check (
            status in (
                'pending',
                'confirmed',
                'rejected',
                'expired'
            )
        ),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- =========================================================
-- WITHDRAWALS
-- =========================================================

create table if not exists public.withdrawals (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null
        references public.profiles(id)
        on delete cascade,
    network text not null
        check (
            network in (
                'TRC20',
                'BEP20'
            )
        ),
    amount_usd numeric(14,2) not null
        check (
            amount_usd >= 50
            and amount_usd <= 50000
        ),
    destination text not null,
    fee_usd numeric(14,2) not null default 0,
    net_amount_usd numeric(14,2) not null default 0,
    status text not null default 'pending'
        check (
            status in (
                'pending',
                'approved',
                'paid',
                'rejected'
            )
        ),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- =========================================================
-- KYC SUBMISSIONS
-- =========================================================

create table if not exists public.kyc_submissions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid unique not null
        references public.profiles(id)
        on delete cascade,
    full_name text not null,
    country text not null,
    document_type text not null,
    document_number text not null,
    verification_step integer not null default 1
        check (
            verification_step between 1 and 2
        ),
    status text not null default 'pending'
        check (
            status in (
                'pending',
                'approved',
                'rejected'
            )
        ),
    submitted_at timestamptz not null default now(),
    reviewed_at timestamptz
);

-- =========================================================
-- REFERRALS
-- =========================================================

create table if not exists public.referrals (
    id uuid primary key default gen_random_uuid(),
    referrer_id uuid not null
        references public.profiles(id)
        on delete cascade,
    referred_user_id uuid unique not null
        references public.profiles(id)
        on delete cascade,
    level integer not null
        check (level between 1 and 3),
    reward_usd numeric(14,2) not null default 0,
    status text not null default 'pending'
        check (
            status in (
                'pending',
                'approved',
                'paid'
            )
        ),
    created_at timestamptz not null default now()
);

-- =========================================================
-- REFERRAL REWARDS
-- =========================================================

create table if not exists public.referral_rewards (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null
        references public.profiles(id)
        on delete cascade,
    source_user_id uuid
        references public.profiles(id)
        on delete set null,
    level integer not null
        check (level between 1 and 3),
    rate_percent numeric(5,2) not null default 0,
    amount_usd numeric(14,2) not null default 0,
    status text not null default 'pending'
        check (
            status in (
                'pending',
                'credited',
                'cancelled'
            )
        ),
    created_at timestamptz not null default now()
);

-- =========================================================
-- DAILY REWARDS
-- =========================================================

create table if not exists public.daily_rewards (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null
        references public.profiles(id)
        on delete cascade,
    order_id bigint
        references public.orders(id)
        on delete set null,
    reward_date date not null,
    rate_percent numeric(5,2) not null default 2,
    amount_usd numeric(14,2) not null default 0,
    status text not null default 'pending'
        check (
            status in (
                'pending',
                'credited',
                'cancelled'
            )
        ),
    created_at timestamptz not null default now(),
    unique(user_id, order_id, reward_date)
);

-- =========================================================
-- TRANSACTIONS
-- =========================================================

create table if not exists public.transactions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null
        references public.profiles(id)
        on delete cascade,
    type text not null
        check (
            type in (
                'deposit',
                'withdrawal',
                'purchase',
                'daily_reward',
                'referral',
                'adjustment'
            )
        ),
    amount_usd numeric(14,2) not null,
    reference_id text,
    description text,
    status text not null default 'completed',
    created_at timestamptz not null default now()
);

-- =========================================================
-- SUPPORT CHANNELS
-- =========================================================

create table if not exists public.support_channels (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    type text not null,
    value text not null,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

-- =========================================================
-- TWO-STEP VERIFICATION
-- =========================================================

create table if not exists public.verification_settings (
    user_id uuid primary key
        references public.profiles(id)
        on delete cascade,
    email_verified boolean not null default false,
    phone_verified boolean not null default false,
    two_factor_enabled boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- =========================================================
-- BIKE PACKAGES
-- =========================================================

insert into public.bike_packages
    (name, bikes, price, amount_usd, status)
values
    ('1 Bike', 1, 50, 50, 'active'),
    ('2 Bikes', 2, 100, 100, 'active'),
    ('4 Bikes', 4, 200, 200, 'active'),
    ('10 Bikes', 10, 500, 500, 'active'),
    ('20 Bikes', 20, 1000, 1000, 'active'),
    ('100 Bikes', 100, 5000, 5000, 'active'),
    ('200 Bikes', 200, 10000, 10000, 'active'),
    ('1,000 Bikes', 1000, 50000, 50000, 'active')
on conflict do nothing;

-- =========================================================
-- SUPPORT CHANNELS
-- =========================================================

insert into public.support_channels
    (name, type, value, active)
values
    ('Telegram', 'telegram', '', true),
    ('Discord', 'discord', '', true)
on conflict do nothing;

-- =========================================================
-- INDEXES
-- =========================================================

create index if not exists idx_profiles_email
    on public.profiles(email);

create index if not exists idx_profiles_referral_code
    on public.profiles(referral_code);

create index if not exists idx_orders_user_id
    on public.orders(user_id);

create index if not exists idx_orders_package_id
    on public.orders(package_id);

create index if not exists idx_rentals_user_id
    on public.rentals(user_id);

create index if not exists idx_deposits_user_id
    on public.deposits(user_id);

create index if not exists idx_withdrawals_user_id
    on public.withdrawals(user_id);

create index if not exists idx_kyc_user_id
    on public.kyc_submissions(user_id);

create index if not exists idx_referrals_referrer_id
    on public.referrals(referrer_id);

create index if not exists idx_referral_rewards_user_id
    on public.referral_rewards(user_id);

create index if not exists idx_daily_rewards_user_id
    on public.daily_rewards(user_id);

create index if not exists idx_transactions_user_id
    on public.transactions(user_id);

-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

alter table public.profiles enable row level security;
alter table public.wallets enable row level security;
alter table public.bike_packages enable row level security;
alter table public.orders enable row level security;
alter table public.rentals enable row level security;
alter table public.deposits enable row level security;
alter table public.withdrawals enable row level security;
alter table public.kyc_submissions enable row level security;
alter table public.referrals enable row level security;
alter table public.referral_rewards enable row level security;
alter table public.daily_rewards enable row level security;
alter table public.transactions enable row level security;
alter table public.support_channels enable row level security;
alter table public.verification_settings enable row level security;

-- =========================================================
-- PUBLIC PACKAGE POLICY
-- =========================================================

drop policy if exists "Anyone can view active bike packages"
on public.bike_packages;

create policy "Anyone can view active bike packages"
on public.bike_packages
for select
to anon, authenticated
using (status = 'active');

-- =========================================================
-- PUBLIC SUPPORT POLICY
-- =========================================================

drop policy if exists "Anyone can view active support channels"
on public.support_channels;

create policy "Anyone can view active support channels"
on public.support_channels
for select
to anon, authenticated
using (active = true);

-- =========================================================
-- USER PROFILE POLICY
-- =========================================================

drop policy if exists "Users can view their own profile"
on public.profiles;

create policy "Users can view their own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

-- =========================================================
-- USER WALLET POLICY
-- =========================================================

drop policy if exists "Users can view their own wallet"
on public.wallets;

create policy "Users can view their own wallet"
on public.wallets
for select
to authenticated
using (auth.uid() = user_id);

-- =========================================================
-- USER ORDERS POLICY
-- =========================================================

drop policy if exists "Users can view their own orders"
on public.orders;

create policy "Users can view their own orders"
on public.orders
for select
to authenticated
using (auth.uid() = user_id);

-- =========================================================
-- USER RENTALS POLICY
-- =========================================================

drop policy if exists "Users can view their own rentals"
on public.rentals;

create policy "Users can view their own rentals"
on public.rentals
for select
to authenticated
using (auth.uid() = user_id);

-- =========================================================
-- USER DEPOSITS POLICY
-- =========================================================

drop policy if exists "Users can view their own deposits"
on public.deposits;

create policy "Users can view their own deposits"
on public.deposits
for select
to authenticated
using (auth.uid() = user_id);

-- =========================================================
-- USER WITHDRAWALS POLICY
-- =========================================================

drop policy if exists "Users can view their own withdrawals"
on public.withdrawals;

create policy "Users can view their own withdrawals"
on public.withdrawals
for select
to authenticated
using (auth.uid() = user_id);

-- =========================================================
-- USER KYC POLICY
-- =========================================================

drop policy if exists "Users can view their own KYC"
on public.kyc_submissions;

create policy "Users can view their own KYC"
on public.kyc_submissions
for select
to authenticated
using (auth.uid() = user_id);

-- =========================================================
-- USER REFERRAL POLICY
-- =========================================================

drop policy if exists "Users can view their own referrals"
on public.referrals;

create policy "Users can view their own referrals"
on public.referrals
for select
to authenticated
using (
    auth.uid() = referrer_id
    or auth.uid() = referred_user_id
);

-- =========================================================
-- USER REWARD POLICIES
-- =========================================================

drop policy if exists "Users can view their own referral rewards"
on public.referral_rewards;

create policy "Users can view their own referral rewards"
on public.referral_rewards
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can view their own daily rewards"
on public.daily_rewards;

create policy "Users can view their own daily rewards"
on public.daily_rewards
for select
to authenticated
using (auth.uid() = user_id);

-- =========================================================
-- USER TRANSACTION POLICY
-- =========================================================

drop policy if exists "Users can view their own transactions"
on public.transactions;

create policy "Users can view their own transactions"
on public.transactions
for select
to authenticated
using (auth.uid() = user_id);

-- =========================================================
-- VERIFICATION POLICY
-- =========================================================

drop policy if exists "Users can view their verification settings"
on public.verification_settings;

create policy "Users can view their verification settings"
on public.verification_settings
for select
to authenticated
using (auth.uid() = user_id);

-- =========================================================
-- DONE
-- =========================================================
